site_name: CHS jsPsych
docs_dir: ./packages
repo_url: https://github.com/lookit/lookit-jspsych

nav:
  - Plugins and Extensions:
      - Record: record/README.md
      - Surveys: surveys/README.md
  - Developers:
      - Data: data/README.md
      - CHS's initJsPsych: lookit-initjspsych/README.md
      - Templates: templates/README.md

not_in_nav: index.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

exclude_docs: |
  node_modules
  CHANGELOG.md
  !templates

theme:
  name: readthedocs
  custom_dir: _custom_theme/

extra_css:
  - css/jspsych_docs.css

extra_javascript:
  - js/links_in_new_tab.js

plugins:
  - search
  - macros

extra:
  jsPsych: https://www.jspsych.org/v8/
