site_name: CHS jsPsych
docs_dir: ./packages
nav:
  - data/README.md
  - lookit-initjspsych/README.md
  - record/README.md
  - surveys/README.md
plugins:
    - search
    - macros
extra:
  jsPsych: https://www.jspsych.org/7.3/