site_name: CHS jsPsych
docs_dir: ./packages
repo_url: https://github.com/lookit/lookit-jspsych

nav:
  - Home: index.md
  - Other Projects:
      - Lookit API: https://lookit.readthedocs.io
      - Ember Lookit Frameplayer: https://lookit.readthedocs.io/projects/frameplayer
  - Trials:
      - Record: record/README.md
      - Surveys: surveys/README.md
  - Additional:
      - Data: data/README.md
      - CHS's initJsPsych: lookit-initjspsych/README.md
      - Templates: templates/README.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

exclude_docs: |
  node_modules
  CHANGELOG.md
  !templates

theme:
  name: readthedocs

plugins:
  - search
  - macros

extra:
  jsPsych: https://www.jspsych.org/v8/
