/** Error for when AWS response is missing attribute. */
export class AWSMissingAttrError extends Error {
  /**
   * Error for when AWS response is missing attribute.
   *
   * @param awsAttrName - Name of missing AWS response attribute.
   */
  public constructor(awsAttrName: string) {
    super(`Response from AWS send is missing an attribute: ${awsAttrName}`);
    this.name = "AWSMissingAttrError";
  }
}

/** Error when the upload part retries run out. */
export class UploadPartError extends Error {
  /**
   * Error when the upload part retries run out.
   *
   * @param error - Error object generated by upload part function.
   */
  public constructor(error?: Error) {
    super(`Upload part failed after 3 attempts: ${error}`);
    this.name = "UploadPartError";
  }
}

/** Error for when the AWS config fails */
export class AWSConfigError extends Error {
  /**
   * AWS cofiguration error. This could be due to incorrect credentials, bucket
   * name, and/or region.
   *
   * @param error - Error object from the AWS response.
   */
  public constructor(error: unknown) {
    let err_msg = "";
    if (error instanceof Error) {
      err_msg = error.message;
    }
    super(`AWS configuration error: ${err_msg}`);
    this.name = "AWSConfigError";
  }
}

/** Error for when URL from Django API is not formatted as expected. */
export class URLWrongError extends Error {
  /** Throw error when URL is not formatted correctly. */
  public constructor() {
    super("URL is different than expected.");
    this.name = "URLWrongError";
  }
}

/** Error for when temporary AWS credentials are not found on the page. */
export class MissingCredentials extends Error {
  /** Throw error when AWS credentials are not found. */
  public constructor() {
    super("AWS credentials for video uploading not found.");
    this.name = "MissingCredentials";
  }
}

/** Error for when temporary AWS credentials have expired. */
export class ExpiredCredentials extends Error {
  /** Throw error when temporary AWS credentials have expired. */
  public constructor() {
    super(
      "The video upload credentials have expired. Please re-start the experiment on the CHS website.",
    );
    alert(
      "Your credentials have expired. Please re-start the experiment on the CHS website.",
    );
    this.name = "ExpiredCredentials";
  }
}
