/** Error for when AWS response is missing attribute. */
export class AWSMissingAttrError extends Error {
  /**
   * Error for when AWS response is missing attribute.
   *
   * @param awsAttrName - Name of missing AWS response attribute.
   */
  public constructor(awsAttrName: string) {
    super(`Response from AWS send is missing an attribute: ${awsAttrName}`);
    this.name = "AWSMissingAttrError";
  }
}

/** Error when the upload part retries run out. */
export class UploadPartError extends Error {
  /**
   * Error when the upload part retries run out.
   *
   * @param error - Error object generated by upload part function.
   */
  public constructor(error?: Error) {
    super(`Upload part failed after 3 attempts: ${error}`);
    this.name = "UploadPartError";
  }
}

/** Error for when the AWS config fails */
export class AWSConfigError extends Error {
  /**
   * AWS cofiguration error. This could be due to incorrect credentials, bucket
   * name, and/or region.
   *
   * @param errorMsg - Message property of error object from the AWS response.
   */
  public constructor(errorMsg: string) {
    super(`AWS configuration error: ${errorMsg}`);
    this.name = "AWSConfigError";
  }
}
