/** Error when the upload part retries run out. */
export class SequenceExpDataError extends Error {
  /**
   * Error when the upload part retries run out.
   *
   * @param error - Error object generated by upload part function.
   */
  public constructor() {
    super("Experiment sequence or data missing.");
    this.name = "SequenceExpDataError";
  }
}
