name: build

on: push

jobs:
  build:
    name: Build, lint, and test on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install pango for NPM package "canvas"
        run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev

      - name: Install NPM dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Lint project
        run: npm run lint

      - name: Format project
        run: npm run format

      - name: Test project
        run: npm test
