name: build

on: push

jobs:
  build:
    name: Build, lint, and test on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install pango for NPM package "canvas"
        run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev

      - name: Install NPM dependencies
        run: npm install --package-lock

      - name: Lint project
        run: npm run lint

      - name: Format project
        run: npm run format

      - name: Build packages
        run: npm run build

      - name: Test project
        run: npm test

      - name: Check for clean git tree
        shell: bash
        run: |
          if [[ $(git status -s) ]]
          then 
              echo "The following files have changed:"
              git status -s
              exit 1
          fi
