name: release

on:
  push:
    paths:
      - ".changeset/**"
      - ".github/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install pango for NPM package "canvas"
        run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish Packages
        id: changesets
        uses: changesets/action@v1
        with:
          version: npx changeset version
          publish: npx changeset publish
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


